name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # # 4. Run tests
      # - name: Run Tests
      #   run: npm test

  deploy:
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/main'

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v5.0.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_PUBLIC_IP }}
        REMOTE_USER: ubuntu
        REMOTE_PORT: 22
        SOURCE: ./
        TARGET: /home/ubuntu/cloud-app
        SCRIPT_AFTER: |
          cd /home/ubuntu/cloud-app
          npm install
          pm2 restart cloud-app || pm2 start app.js --name cloud-app

